
# Site settings
title: Alexia's Blog
description: A blog about web design in society.
baseurl: "/Blog" # folder where your site lives, e.g. /web1-sp - needs to start with a slash
url: "https://alexiaml.github.io/" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
